bindAddr = "0.0.0.0"
bindPort = 5010
#kcpBindPort = 5010
quicBindPort = 5010

vhostHTTPPort = 80
vhostHTTPSPort = 443

auth.method = "token"
auth.token = "12345678"

webServer.addr = "0.0.0.0"
webServer.port = 5011
webServer.user = "admin"
webServer.password = "admin"
webServer.pprofEnable = false

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = false

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

maxPortsPerClient = 8
udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168
